name: Docker CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: false
        tags: local/dev:latest

    - name: Compose Up
      run: docker compose up -d --build




    - name: 🐳 Установка Docker и docker-compose
      run: curl -fsSL https://get.docker.com -o get-docker.shsh get-docker.sh
        sudo apt-get install docker-compose-plugin -y
